MacOS install instructions
naturalcrit/homebrewery pull request #1716
Opened 2021-09-28 00:12 UTC by Gazook89

I went through the process of getting Homebrewery working on MacOS *without* using Docker and documented my effort, which is now this readme.md.  Some of the steps I already had in place such as installation of git and node, so I haven't been able to test all the steps as I've written them, but I'm pretty confident it is correct.  Until the whole process is confirmed by one or more people though, this is a draft.  

It is rather wordy compared to the main repo readme, but I wrote it with much more depth for near-beginners.  Mostly this was for my benefit as a near-beginner myself so I can go back and see what I did in case I need to.

I am *very* happy to get pointers to make all of this easier.

@Gazook89 To complete before merging:

- [ ] Add a link in the main readme.md
- [ ] Remove Step 8 (V3 is now enabled in the repo by default)
- [ ] Apply other reviewer comments

2021-12-03 20:50 UTC, calculuschild requested changes
Just a couple things. Sorry this has taken so long to review.

I'm just going to trust you on most of the Mac-specific stuff because I don't have a way to verify it.

2021-12-03 20:50 UTC, calculuschild commented on README.macOS.md
> +Homebrew is a *package manager* for macOS and Linux, and we will use it to install NodeJS, MongoDB, and git.  You likely will need to be an Administrator on your machine.
Can you add a couple words to just clarify that Homebrew is not the same as the Homebrewery? Somebody is going to get confused I'm sure.

2021-12-03 20:50 UTC, calculuschild commented on README.macOS.md
> +
I think v3 is now in the config file.

2022-01-04 20:26 UTC, calculuschild commented
@Gazook89 Do you think we can finish this one off? It's been sitting for a while. Or perhaps @G-Ambatte if you want to contribute to this as part of #1904

2022-01-13 02:41 UTC, Gazook89 commented on README.macOS.md
> +- type db.brews.find().pretty() to display a list of the documents in the "brews" collection...you should get one result back, the document you just created.
this should be `db.brews.find().pretty()`  (just put that in a code block).

2022-01-22 16:41 UTC, calculuschild commented
@Gazook89 I see you updated this some more. Any chance we can address my remaining comments and merge this?

2022-02-04 17:04 UTC, Gazook89 commented
So i haven't been able to get HB working locally again (without using Docker, which I haven't tried since I had it installed not with docker).   I'm not sure if I've just screwed up the environment too much, or something changed in HB that I can't figure out, but either way the instructions above haven't been able to help me with the reinstall.  Additionally, I think there are steps in this that are superfluous, but I can't figure out exactly which ones.

Until I am able to learn more about the underlying issues I can't really vouch for this PR as-is, so I suggest that it is closed as unfinished for now.  I have been working on other projects solely to learn javascript lately, and soon-ish will start trying to learn backend stuff and thus more about environments etc.....so someday I'll maybe have a good enough grip to come back to this PR(?)

2022-02-04 18:26 UTC, calculuschild commented
Sounds good. I'll close it for now then.

2022-02-04 18:26 UTC, closed without merging

2023-10-16 00:11 UTC, Gazook89 commented on README.macOS.md
> +- Now you should be able to run the shortcuts.  In the Terminal, run `brew services status` and after hitting Enter you should get a list of services running and their status (if you started your Mon
confirmed the above comment is true as i follow my own install instructions again.

2023-10-16 00:17 UTC, Gazook89 commented on README.macOS.md
> +- type db.brews.find().pretty() to display a list of the documents in the "brews" collection...you should get one result back, the document you just created.
line 54 gets this error:
```zsh
This gets an error about deprecation:
```zsh
homebrewery> db.brews.insert({"title":"test"})
DeprecationWarning: Collection.insert() is deprecated. Use insertOne, insertMany, or bulkWrite.
```