Fix QR code snippet when `brew.shareId` doesn't exist
naturalcrit/homebrewery pull request #1724
Opened 2021-09-30 22:50 UTC by G-Ambatte

This PR modifies the snippet generator for the QR code to use the URL for the Homebrewery home page when a `shareId` does not currently exist.

2021-09-30 23:35 UTC, calculuschild requested changes
Can you use `dedent` to clean up the formatting a little? (Instead of the plus signs concatenating everything)

2021-10-01 00:01 UTC, calculuschild requested changes
Oh shoot. I guess this does need to stay on a single line in the output. I misread.

Can you go back to not using dedent and put the plus signs back at the end of lines as needed so the output is one single line? That's my fault. Otherwise looks fine.

2021-10-01 00:05 UTC, G-Ambatte commented
Reverted the `dedent` commit, so back to original now.

2021-10-01 01:06 UTC, calculuschild approved these changes

2021-10-01 01:06 UTC, calculuschild commented on client/homebrew/editor/snippetbar/snippets/snippets.js
> +							`https://homebrewery.naturalcrit.com` + `${brew.shareId ? `/share/${brew.shareId}` : ''}` +
```suggestion
							`https://homebrewery.naturalcrit.com${brew.shareId ? `/share/${brew.shareId}` : ''}` +
```

2021-10-01 01:07 UTC, merged

2021-10-01 01:08 UTC, calculuschild commented
Thanks @G-Ambatte ! 🎉

2021-10-01 01:12 UTC, G-Ambatte commented
Looks like it's working fine on the staging site!