drop shadow filter to text stroke
naturalcrit/homebrewery pull request #3428
Opened 2024-04-25 13:11 UTC by 5e-Cleric

This PR fixes the long standing issue with text stroke, as chrome finally fixed paint-order.

Now we don't need the 12 drop shadows to fake it. Although it could look better. An svg filter might be preferred:

![image](https://github.com/naturalcrit/homebrewery/assets/91662974/ef2e608a-1bf7-4c1f-a2da-a3434eb964c8)

2024-04-25 13:32 UTC, calculuschild commented
I think this does look better actually. Nice crisp lines instead of the rounded corners and the fuzzy edges.  This biggest artifact I see is on the left serif of the T, which doesn't seem to appear on the right one. Might be a small  in the font itself, which we can try to fix.

We had a similar issue with the last time we tried this (when we discovered `paint-order` wasn't working) and changing the CSS might have revealed some characters we missed. Essentially some line definitions lines overlapping or protruding in a way that isn't visible until you apply a stroke.

https://github.com/naturalcrit/homebrewery/pull/2061#issuecomment-1066040732

Luckily I wrote down the adjustment steps a few comments below that so I can try tweaking the T and see if the weird prong goes away. But that just might be how it is, and I think I'm ok with that.

2024-04-25 13:38 UTC, calculuschild requested changes

2024-04-25 13:38 UTC, calculuschild commented on themes/V3/5ePHB/style.less
> +		-webkit-text-stroke: 8px black;
Can we set these to use `cm`?

2024-05-01 19:58 UTC, 5e-Cleric commented on themes/V3/5ePHB/style.less
> +		-webkit-text-stroke: 8px black;
done

2024-05-01 21:21 UTC, calculuschild commented
I think this is good. Thanks @5e-Cleric !

2024-05-01 21:21 UTC, merged