Modify PrintPage to use new BrewRenderer methods
naturalcrit/homebrewery pull request #3464
Opened 2024-05-09 04:59 UTC by G-Ambatte

This PR resolves #3435.

This PR modifies the Print Page to use the BrewRenderer to render the pages for printing. This ensures that the Print Page output will always match the Share and Edit Page visual outputs - previously it used a duplicated section of code that was not updated when the BrewRenderer was changed.

Some modifications have also been made to the BrewRenderer, including the option to not render inside an iFrame (defaults to iFrame on), and a method to indicate to Print Page when the print event should fire (i.e. on completion of document rendering).

iFrame rendering would be preferable but while it is possible to create functions to print the iFrame content directly, I have been unable to get printing via Ctrl+P or selecting Print from the browser menu to work correctly. For this reason, the brew renders outside of a frame on Print Page.

2024-05-09 05:03 UTC, 5e-Cleric commented
will review this as soon as i get my hands on a computer

2024-05-13 17:51 UTC, calculuschild requested changes

2024-05-15 15:45 UTC, calculuschild commented on client/homebrew/brewRenderer/brewRenderer.jsx
> +		frame             : true,
```suggestion
		useIFrame         : true,
```

2024-05-16 23:31 UTC, G-Ambatte commented on client/homebrew/brewRenderer/brewRenderer.jsx
> +		frame             : true,
Applied in the latest commit.

2024-05-16 23:38 UTC, G-Ambatte commented on client/homebrew/pages/printPage/printPage.jsx
> -			<Meta name='robots' content='noindex, nofollow' />
Good catch, I've added this back in the latest commit.

2024-05-16 23:40 UTC, G-Ambatte commented on client/homebrew/pages/printPage/printPage.jsx
> +	frameMounted : function() {
I've applied this change in the latest commit, PR should be updated now.

2024-05-16 23:44 UTC, G-Ambatte commented on client/homebrew/brewRenderer/brewRenderer.jsx
> +			if((props.renderAllPages || isInView(index) || !renderedPages[index]) && typeof window !== 'undefined'){
I realized that using `!props.frame` as a check to render a page was particularly opaque, so I have introduced a new prop `renderAllPages` to make it clearer that all pages will be rendered from the Print Page.

2024-05-17 00:40 UTC, G-Ambatte commented
I'm getting a weird case where headings are not rendered at the time the print dialog is first called, so they are missing from the output. 
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/0c7067f8-f525-4b29-a1fa-0ca9a4058660)

However, closing the print dialog and pressing Ctrl+P or even reloading the page works fine.
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/e76851fc-939c-4a9c-a0ab-5babc6baf0c9)

I'm still digging into it.

2024-05-17 19:14 UTC, calculuschild commented
> Serious question, why did we agree on keeping this instead of printing from `/edit` or `/share`?

I'm not sure I understand the question. Printing HTML to PDF prints the entire page, so you need to somehow generate a separate window/frame. As far as I know you can't just send a single element to the printer.

2024-05-17 19:16 UTC, 5e-Cleric commented
> > Serious question, why did we agree on keeping this instead of printing from `/edit` or `/share`?
> 
> I'm not sure I understand the question. Printing is possible from both /edit and /share via the "get PDF" button.
> 
> Printing HTML to PDF prints the entire page, so you need to somehow generate a separate window/frame. As far as I know you can't just send a single element to the printer.

try this:

In the brew style tab:
```
@media print {
	.brewRenderer {
		height: 100%;
		overflow-y: unset;
		.pages {
			margin: 0px;
			&>.page {
			box-shadow: unset;
			}
		}
	}
}
```

In the dev tools console:

window.frames['BrewRenderer'].contentWindow.print()

2024-05-17 19:28 UTC, calculuschild commented
Well if that works, that would simplify things a lot. Does it still work with variables across pages? Work with Legacy brews? I'm ok doing that if we can eliminate the whole `/print` page.

2024-05-17 19:35 UTC, 5e-Cleric commented
First one for sure, second haven't tried, should work fine

2024-05-17 19:50 UTC, 5e-Cleric commented
Issue #2742 tracks printing without print page

2024-05-17 20:28 UTC, calculuschild commented
Wow, I don't remember that issue at all, but I guess I was there. Looks like the main concern was keeping existing `/print` links working, but now that it's been a while I don't know how necessary that is. I used a few `/print` links to share minimal error examples with Google, but those ones have been solved. The other use case from @ericscheid was for the `visualping` tool which periodically scans a webpage for visual differences so you can be alerted to updates. It wouldn't work in `/share` because it only loads the outer frame or something.

2024-05-17 21:49 UTC, G-Ambatte commented
As I recall, the print function didn't trigger a full render so PPR would break the print. I think that's no longer an issue with the changes to Brew Renderer, so the logic may no longer apply.

2024-05-18 21:26 UTC, calculuschild commented
Yeah, looks like the `@media print {` approach does work with variables and legacy brews. If we are in agreement, I say we close this PR and move instead to that as a simpler alternative.

2024-05-22 17:50 UTC, calculuschild commented
I am pulling new PR together for this now.

2024-05-22 20:00 UTC, closed without merging