Solve for .descriptive and .wide not getting along
naturalcrit/homebrewery pull request #3517
Opened 2024-06-05 22:46 UTC by dbolack-ab

Uses suggested fix from Issue

Uses more more direct target rather than rearrange the file.

Solves #2688

2024-06-05 23:03 UTC, 5e-Cleric approved these changes

2024-06-16 00:26 UTC, G-Ambatte requested changes
This does NOT fix the reported issue; checking the reproduction text in the deployment shows that the issue still exists.
I believe the issue reporter made a typo when suggesting the correction, instead of `.page .descriptive.wide {`, they should have entered `.page .descriptive.wide + * {`.

Current behaviour in Production: 
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/a3fb7d80-9dee-442d-9f44-574469254325)

Current behaviour in Test Deployment:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/4c39bcb1-5e72-4b21-97c8-bc4a9c2c3acc)

Behaviour with suggested change:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/bc80fd3d-8b33-45c7-b29a-e088d62966a5)

2024-06-20 00:29 UTC, dbolack-ab commented
> This does NOT fix the reported issue; checking the reproduction text in the deployment shows that the issue still exists. I believe the issue reporter made a typo when suggesting the correction, instead of `.page .descriptive.wide {`, they should have entered `.page .descriptive.wide + * {`.
> 
> Current behaviour in Production: ![image](https://private-user-images.githubusercontent.com/19826659/340052004-a3fb7d80-9dee-442d-9f44-574469254325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzkyMTEsIm5iZiI6MTcxODgzODkxMSwicGF0aCI6Ii8xOTgyNjY1OS8zNDAwNTIwMDQtYTNmYjdkODAtOWRlZS00NDJkLTlmNDQtNTc0NDY5MjU0MzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIzMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNDFkMjhiYTQ4YmM0YjFhNmZmNzMxZmMwZjZkYzQ5YjVhNWE2YzhiYmI1ZjliZDRmYzYxOTliYTc5ODdjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RxHuSciCAWEQp4qaZa8L3dqR7e0vwSQOfVS-LzfFAt4)
> 
> Current behaviour in Test Deployment: ![image](https://private-user-images.githubusercontent.com/19826659/340052021-4c39bcb1-5e72-4b21-97c8-bc4a9c2c3acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzkyMTEsIm5iZiI6MTcxODgzODkxMSwicGF0aCI6Ii8xOTgyNjY1OS8zNDAwNTIwMjEtNGMzOWJjYjEtNWU3Mi00YjIxLTk3YzgtYmM0YTljMmMzYWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIzMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMzIzOWYwNzU5ZTM4NmMzM2UzMGIxYzcxNzc1ZWQ2MzA5ZmIwMTA1ZTUxOGY3YmVlNGUyODBhZTFmMmU1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JFyPS9KRbKg0XhXf9IoZP3xTaIxSl0LoRwUX7pLiPk)
> 
> Behaviour with suggested change: ![image](https://private-user-images.githubusercontent.com/19826659/340052033-bc80fd3d-8b33-45c7-b29a-e088d62966a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzkyMTEsIm5iZiI6MTcxODgzODkxMSwicGF0aCI6Ii8xOTgyNjY1OS8zNDAwNTIwMzMtYmM4MGZkM2QtOGIzMy00NWM3LWIyOWEtZTA4OGQ2Mjk2NmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIzMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGZkODZhODUxMThjY2JlYTJkYTJiN2Y1ZWM0OWMyNzRmMGMyZTI3OWI3YzdlMzI5YzJmM2RkNGQ5MWVhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zyzokLtORWyp9S4Gs18f9DUniMECkGktsJWHO617OEw)

Fixed. Note sure why it looked right before but it definitely did not on reload today.

2024-08-01 04:58 UTC, calculuschild commented
Looks good @dbolack-ab ! Merging!

2024-08-01 04:59 UTC, merged