Add disableMeta prop to SharePage
naturalcrit/homebrewery pull request #3588
Opened 2024-07-21 01:37 UTC by G-Ambatte

This PR resolves #3586.

This PR adds the `disableMeta` prop to the SharePage.

`disableMeta` defaults to `false`.
When `true`, the `<MetadataNav>` component is removed from the output of `sharePage.jsx`, and the `brewTitle` styling is tweaked to remove the cursor changes.

2024-08-01 19:58 UTC, calculuschild requested changes

2024-08-01 19:58 UTC, calculuschild commented on client/homebrew/homebrew.jsx
>  						<Route path='/migrate' element={<WithRoute el={SharePage} brew={this.props.brew} />} />
Let's also add this to `/migrate`

2024-08-09 06:05 UTC, G-Ambatte commented on client/homebrew/homebrew.jsx
>  						<Route path='/migrate' element={<WithRoute el={SharePage} brew={this.props.brew} />} />
Done!

2024-08-09 14:55 UTC, merged

2024-08-09 14:55 UTC, calculuschild commented
Thanks @G-Ambatte !