Relocate general purpose snippets still in 53PHB theme to Blank
naturalcrit/homebrewery pull request #3664
Opened 2024-08-23 19:27 UTC by dbolack-ab

This relocates a significant number of Snippets from the V3/5ePHB theme to the V3/Blank theme

- Text Editor Menu
  -  Table of Contents
  -  Index
-  Style Editor Menu
  - Remove Drop cap
  - Tweak Drop cap

It also removes redundant entries:
- Images Menu
  - Image
  - Background Image
  - Watermark

2024-08-23 19:32 UTC, 5e-Cleric commented
>Remove Drop cap
Tweak Drop cap

We should then add a drop cap to the blank theme as well, probably not a bad idea.

2024-08-24 09:23 UTC, 5e-Cleric commented
Hey hey hey! the styles for the cover page should remain in the PHB theme! Those fonts and assets are from the phb theme, Blank should have a cover, but neither the markdown nor the less should be the same as in the PHB

2024-10-28 18:12 UTC, dbolack-ab commented
> Hey hey hey! the styles for the cover page should remain in the PHB theme! Those fonts and assets are from the phb theme, Blank should have a cover, but neither the markdown nor the less should be the same as in the PHB

I reverted this back then but it leads me to questions:

1) Should Blank be the base theme that is loaded for *Homebrewery* ( not Brews, but the app ) instead of 5ePHB? Or should we establish a distinct *Homebrewery* theme that decouples this from the Brew theme ( even if it is initially indistinct ). I know this is  a little bit of a tangent to this PR and probably should be handled as a distinct task - but it factors into the thinking

2) Regarding the styles and such that were moved, I will clone those, lacking the font definitions for now. We may want to have a separate discussion as to if we want specific faces to be the defaults for Blank as opposed to system/browser defaults.

2024-10-28 21:26 UTC, 5e-Cleric commented
> questions:
> 
> 1. Should Blank be the base theme that is loaded for _Homebrewery_ ( not Brews, but the app ) instead of 5ePHB? Or should we establish a distinct _Homebrewery_ theme that decouples this from the Brew theme ( even if it is initially indistinct ). I know this is  a little bit of a tangent to this PR and probably should be handled as a distinct task - but it factors into the thinking

There has been discussion about this, but we have never reached a full consensus, first, we want to decouple the HB from the brews, meaning, style for both should be kept separate, the blank theme only contains CSS for the brews.

Even if we made a Homebrewery theme, we should keep blank, for other themes to be built over it without having to worry about little stuff, this is my personal opinion, and, i believe, the team's(if i recall correctly)

I believe we should improve the blank theme to a more apt version of itself, adding covers and a TOC styling should help, but we don't need to make more changes than necessary, and changing the blank theme would today impact all themes out there, so also all brews out there.

We are open to talk about this, definitely.

> 2. Regarding the styles and such that were moved, I will clone those, lacking the font definitions for now. We may want to have a separate discussion as to if we want specific faces to be the defaults for Blank as opposed to system/browser defaults.

I will assume that by faces you mean typefaces, yeah, not sure either of what the blank theme styling should be.

2025-02-11 19:34 UTC, calculuschild commented
> 1. Should Blank be the base theme that is loaded for _Homebrewery_ ( not Brews, but the app ) instead of 5ePHB? Or should we establish a distinct _Homebrewery_ theme that decouples this from the Brew theme ( even if it is initially indistinct ). I know this is  a little bit of a tangent to this PR and probably should be handled as a distinct task - but it factors into the thinking

BLANK is intended to be used as the base for *all document themes on the entire site*, including built-in themes and user themes. It does not specify any stylistic choices, but ensures basic feature functionality so all themes can make use of them. I.e., every theme should have bold and italics working without having to define that separately. All themes should have access to image masks. All themes should have working column breaks, etc.

So a "Homebrewery" theme would also be built upon BLANK as it needs it for basic functionality. But yes eventually we want two "Homebrewery" themes:

1) Site UI (we kind of have this on `listPage.less` and `uiPage.less`, which is visible on `/account` and our error pages). This would be used in the changeLog and userBrews pages, possibly the FAQ, etc. I.e. any "documents" that are part of the app.

2) An actual Homebrewery "RPG document" theme we can offer as the default instead of WOTC stuff (the Journal theme is great, but pretty niche).

> 2. Regarding the styles and such that were moved, I will clone those, lacking the font definitions for now. We may want to have a separate discussion as to if we want specific faces to be the defaults for Blank as opposed to system/browser defaults.

BLANK should not define any stylistic choice like fonts, except in specific cases where a font should be consistent across all themes (Naturalcrit branding, etc.), or to make a feature minimally functional (we set a base font size to make the different Header levels distinct, and add basic indentation to lists, for example).

A user should be able to take BLANK as a base, and change the font of the entire document with minimal conflict. Unlike trying to build a theme on top of 5ePHB where you have to overwrite fonts in 32 different places.

However note BLANK isn't using browser defaults. It does pull from `/shared/naturalcrit/styles/core.less`, which is the same base the rest of the site uses. So we at least guarantee that every browser will be seeing the same defaults.

2025-02-11 19:38 UTC, calculuschild requested changes
Added some comments. Mostly some things need to be kept back in the PHB theme.

2025-02-11 19:38 UTC, calculuschild commented on themes/V3/5ePHB/style.less
> -		font-size : 0.218cm;
Another one where BLANK probably shouldn't set a specific font size.

2025-02-11 19:44 UTC, calculuschild commented
> We should then add a drop cap to the blank theme as well, probably not a bad idea.

If we decide we want the snippet in BLANK, then we need some minimal functional CSS to make it work.

2025-02-11 20:40 UTC, dbolack-ab commented on themes/V3/5ePHB/style.less
> -	.toc {
The PHB stylings for the ToC seemed pretty universal to me - or at least a sensible default.

2025-02-11 20:46 UTC, dbolack-ab commented on themes/V3/5ePHB/style.less
> -.monster,
Moved back to PHB

2025-02-11 20:46 UTC, dbolack-ab commented on themes/V3/5ePHB/style.less
> -					font-family : 'BookInsanityRemake';
Removed in Blank

2025-02-11 20:46 UTC, dbolack-ab commented on themes/V3/5ePHB/style.less
> -					color       : #000000;
Removed in Blank

2025-02-11 20:47 UTC, dbolack-ab commented on themes/V3/5ePHB/style.less
> -		font-size : 0.218cm;
Removed in Blank

2025-02-11 20:50 UTC, dbolack-ab commented
For the larger sections ( index, table of contents ) where there were comments about not using some attributes in BLANK after having been moved to BLANK I have restored the style to 5ePHB while leaving the edited version in BLANK because it should be there as well.

At some point deduping properties that are shared values between the two should be trimmed from PHB, but I think that should wait until consensus occurs on what values BLANK should not have teh same default as PHB.

2025-03-22 15:20 UTC, 5e-Cleric commented
A few changes (i'm sorry to be dragging this one)

Tweak and Remove Drop cap (from the style editor snippets) do not make sense in blank where there isn't any drop cap.

Let's leave them at the phb for now.

with that change done, i will merge this, ideally today.

2025-03-24 12:14 UTC, merged