Permit the \page Token to accept {} values.
naturalcrit/homebrewery pull request #3899
Opened 2024-11-19 21:15 UTC by dbolack-ab

## Description

This PR allows users to apply style, class, and attribute values via the inline `{}` format to the base page for common inheritance.

To Do:
 - [ ] Fix Attributes, They are not being inserted
 - [ ] Add Tests

Usage:
Similar to an inline single mustache.

`\page{wide,banna=fail,color:black}`

*Reviewers, refer to this list when testing features, or suggest new items *
- [ ] Verify new features are functional
  - [ ] Adding a style includes a style on the <div class='page'> instance.
  - [ ] Adding a class includes a class on the <div class='page'> instance.
  - [ ] Adding an HTML Attribute adds the attribute on the <div class='page'> instance.
  - [ ] Mixed forms of above work as expected
- [ ] Verify old features have not broken
  - [ ] `\page` works without values.
- [ ] Test for edge cases / try to break things
  - [ ] Ensure CSS Properties ( --FOO ) can be set.
- [ ] Identify opportunities for simplification and refactoring
- [ ] Check for code legibility and appropriate comments

<details><summary>Copy this list</summary>

2024-11-19 21:34 UTC, calculuschild commented
Is there a concern that this doesn't apply to the very first page which doesn't have a `/page` break?

2024-11-19 23:19 UTC, dbolack-ab commented
> Is there a concern that this doesn't apply to the very first page which doesn't have a `/page` break?

No, though the included code also tolerates putting a `\page`  as the very first line for the occasion that is desirable ( this functionally moves \page to being a START-OF-PAGE instead of END-OF-PAGE marker.

2024-11-20 03:39 UTC, calculuschild commented
Would you mind creating an issue for this PR? So we have a place to document and discuss the problem this is aiming to solve.

2024-11-22 22:36 UTC, 5e-Cleric commented
> > Is there a concern that this doesn't apply to the very first page which doesn't have a `/page` break?
> 
> No, though the included code also tolerates putting a `\page` as the very first line for the occasion that is desirable ( this functionally moves \page to being a START-OF-PAGE instead of END-OF-PAGE marker.

I cannot see this working in the deployment, although the rest seems to work fine.

While this syntax works for us, it is also worth mentioning that codemirror stops processing that line as a `.pageLine`, so we have no way of targeting that element for code highlight.

IF we did it like with tables, that you need the injection to be in the next line:

```
\page
{background:red}
```

That should preserve the code hightlight, and be somewhat intuitive and consistent.

I wish we could keep it in the line though

2024-11-23 07:01 UTC, dbolack-ab commented
> > > Is there a concern that this doesn't apply to the very first page which doesn't have a `/page` break?
> > 
> > 
> > No, though the included code also tolerates putting a `\page` as the very first line for the occasion that is desirable ( this functionally moves \page to being a START-OF-PAGE instead of END-OF-PAGE marker.
> 
> I cannot see this working in the deployment, although the rest seems to work fine.

What can you not see?

Regarding the syntax highlighting - yes, that's not there yet.

2024-11-23 13:19 UTC, 5e-Cleric commented
> What can you not see?

adding `{background:red}` at the begginging of the document does not work.

2024-11-25 01:06 UTC, dbolack-ab commented
> > What can you not see?
> 
> adding `{background:red}` at the beggining of the document does not work.

No. It won't. This syntax *only* works on a `\page` line as described in usage.

2024-11-25 02:16 UTC, Gazook89 commented
For the first page, @5e-Cleric :

<img width="462" alt="image" src="https://github.com/user-attachments/assets/d2758dbf-3aaa-417f-b191-0133cdf66075">

2024-11-25 02:21 UTC, Gazook89 commented
Also, I'll just add this discussion that was on this same topic, before we started using named spans and `:has()` css selector: https://github.com/naturalcrit/homebrewery/issues/1489.  I don't know if it adds anything but it bothered me that I could half-remember talking about this but not the details.

2024-11-25 03:13 UTC, calculuschild commented
> the included code also tolerates putting a \\page as the very first line for the occasion that is desirable ( this functionally moves \\page to being a START-OF-PAGE instead of END-OF-PAGE marker.

Is there any risk of this breaking existing brews? I'm not sure if there would be any documents out there depending on a `\page` at the start to make a blank page. Probably not common, right?

2024-11-25 07:28 UTC, 5e-Cleric commented
> Is there any risk of this breaking existing brews? I'm not sure if there would be any documents out there depending on a `\page` at the start to make a blank page. Probably not common, right?

This should break no document. I have never seen or heard, or can think of any good reason to have an empty page at the top.

2024-12-09 20:40 UTC, 5e-Cleric commented
> While this syntax works for us, it is also worth mentioning that codemirror stops processing that line as a `.pageLine`, so we have no way of targeting that element for code highlight.
> 
> IF we did it like with tables, that you need the injection to be in the next line:
> 
> ```
> \page
> {background:red}
> ```
> 
> That should preserve the code hightlight, and be somewhat intuitive and consistent.
> 
> I wish we could keep it in the line though

The rest of my comment still stands, this breaks the highlight in an irrecuperable way, could we consider that other syntax?

2025-01-11 22:39 UTC, 5e-Cleric commented on client/homebrew/brewRenderer/brewRenderer.jsx
> +			};
Suggested by the toaster, looks cleaner. 

```suggestion
			// I assume there is a prettier way to do this.
const styles = (() => {
    const rawStyles = brewTemplates[index]?.attr?.styles || "";
    const declaredStyles = Object.fromEntries(
        rawStyles.split(";").map(style => {
            const [key, value] = style.split(":").map(s => s?.trim());
            return key && value ? [key, value] : [];
        }).filter(entry => entry.length)
    );

    return {
        ...declaredStyles,
        ...(displayOptions.pageShadows ? {} : { boxShadow: "none" }),
        // Add more conditions as needed
    };
})();

```

2025-01-15 08:37 UTC, 5e-Cleric commented on client/homebrew/brewRenderer/brewRenderer.jsx
>  /*eslint max-lines: ["warn", {"max": 300, "skipBlankLines": true, "skipComments": true}]*/
no need for two separate rules for eslint, decide on one.

2025-01-15 13:10 UTC, dbolack-ab commented on client/homebrew/brewRenderer/brewRenderer.jsx
>  /*eslint max-lines: ["warn", {"max": 300, "skipBlankLines": true, "skipComments": true}]*/
This is what I get for letting VSCode resolve the warning. :)

2025-01-15 19:09 UTC, calculuschild commented on client/homebrew/brewRenderer/brewRenderer.jsx
> +			};
But use tabs.

2025-01-15 19:24 UTC, calculuschild requested changes
A couple things noted just testing quickly:

- The page number at the end of a `/page` becomes inaccurate if it is placed at the first line:

![image](https://github.com/user-attachments/assets/fd49ff1a-3df6-4dea-b9ec-b65a2ab60188)

- The "Jump" buttons are similarly broken in this case. Trying to jump from editor to brewRenderer will crash the page because it tries to jump to a page number that doesn't exist.

2025-01-15 22:40 UTC, dbolack-ab commented
> A couple things noted just testing quickly:
> 
> * The page number at the end of a `/page` becomes inaccurate if it is placed at the first line:
> * The "Jump" buttons are similarly broken in this case. Trying to jump from editor to brewRenderer will crash the page because it tries to jump to a page number that doesn't exist.

I have this solved - though there may be a more clever way to handle it.

2025-01-17 18:40 UTC, calculuschild commented
> // There is bound to be a more elegant way to do this. But this works for now.

I think I see a way to do this and keep it all inside of `markdown.js` so we don't need to duplicate the tag handling in `brewRenderer.jsx`. Let me poke at it a bit before we merge.

2025-01-21 13:39 UTC, 5e-Cleric commented
@calculuschild should we merge? did you advance in your attempt?

2025-01-21 14:02 UTC, calculuschild commented
Please don't merge yet. I was out of town over the weekend and have not implemented yet. If i am right my solution would reduce this PR to ~10 lines.

2025-01-21 18:06 UTC, dbolack-ab commented
> > // There is bound to be a more elegant way to do this. But this works for now.
> 
> I think I see a way to do this and keep it all inside of `markdown.js` so we don't need to duplicate the tag handling in `brewRenderer.jsx`. Let me poke at it a bit before we merge.

I will look at this again and see if I can remember *why* exactly I duplicated it.

2025-01-24 16:27 UTC, closed without merging